### ISSUE TITLE
getPackagePaths.js is requiring fast-glob but the latter is not a dev dependency

### ISSUE THREAD

**Issue by avipie** [microsoft/workspace-tools#301]
$ react-native rnx-bundle --dev false
info Bundling macos...
                    Welcome to Metro!
              Fast - Scalable - Integrated

Failed to construct transformer:  Error: Cannot find module 'fast-glob'
Require stack:
- C:\Users\avipie\Repos\1JS\src\ooui\.store\workspace-tools@0.34.6-c3b5dfdc8c6e3058385c\node_modules\workspace-tools\lib\getPackagePaths.js
- C:\Users\avipie\Repos\1JS\src\ooui\.store\workspace-tools@0.34.6-c3b5dfdc8c6e3058385c\node_modules\workspace-tools\lib\workspaces\implementations\pnpm.js
- C:\Users\avipie\Repos\1JS\src\ooui\.store\workspace-tools@0.34.6-c3b5dfdc8c6e3058385c\node_modules\workspace-tools\lib\index.js

**Comment by ecraig12345** [comment]
Fixed in #307
