### ISSUE TITLE
support yarn version 2

### ISSUE THREAD

**Issue by vignanl** [microsoft/workspace-tools#36]
Projects which use Yarn version 2 are facing caching issue with [lage](https://github.com/microsoft/lage)  because there is a logical dependency of parsing yarn lock file in workspace-tools. current workspace-tools can only parse lock files of yarn version 1, it breaks for yarn version 2 lock files.

#https://github.com/microsoft/lage/issues/129

**Comment by axelhzf** [comment]
It looks like parsing yarn2 is possible with the `@yarnpkg/core` package

https://github.com/snyk/nodejs-lockfile-parser/pull/75/files#diff-b2c66eb5bb9dd1c3dc4998a5d18767af92cc71cd287f5b115a8a602dfc7a275aR27

And here is how to test the lockfile version

https://github.com/snyk/nodejs-lockfile-parser/pull/75/files#diff-d5a4b3a0309f2337144861084c1014523cced561eb722cb9684c63f5e41e0567R120

If using an external library is an option, https://github.com/snyk/nodejs-lockfile-parser can parse lockfiles in several formats including yarn2.

**Comment by shaulgo** [comment]
Are there any plans to fix this?

**Comment by kenotron** [comment]
The external lockfiles parser would be okay if it's relatively clean and simple (and well maintained)!
