### ISSUE TITLE
fetchRemoteBranch fails if using an SSH key with a passphrase to authenticate to remote 

### ISSUE THREAD

**Issue by DrewHigginsMSFT** [microsoft/workspace-tools#76]
When trying to use beachball to generate a change file, I saw that the call to fetch changes from the upstream repo was failing in the call to the fetchRemoteBranch in workspace-tools:

```
Checking for changes against "origin/main"
fetching latest from remotes "origin/main"
beachball v2.16.0 - the sunniest version bumping tool
An error has been detected while running beachball!
Error: Cannot fetch remote: origin main
    at Object.fetchRemoteBranch (C:\code\react-native-windows\node_modules\beachball\node_modules\workspace-tools\lib\git.js:109:15)
```

However, removing the passphrase from the SSH key I used to authenticate to the origin remote repo fixes the command. It seems the the fetchRemoteBranch command fails when the git CLI prompts for the key passphrase.

**Comment by ecraig12345** [comment]
Sorry nobody responded to this sooner. I don't think this is possible to fix, at least without extensive changes. A workaround for the `beachball change` command would be to add the `--no-fetch` argument.
